In [9]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [12]:
df_2024_1 = pd.read_csv('2024.1.csv', sep=';', decimal=',')
df_2024_2 = pd.read_csv('2024.2.csv', sep=';', decimal=',')
df_2025_1 = pd.read_csv('2025.1.csv', sep=';', decimal=',')
df_2025_2 = pd.read_csv('2025.2.csv', sep=';', decimal=',')

C:\Users\felipe.espirito\AppData\Local\Temp\ipykernel_12504\4053130923.py:3: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Unidade de Medida, 13: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_1 = pd.read_csv('2025.1.csv', sep=';', decimal=',')

In [13]:
df = pd.concat([df_2024_1, df_2024_2,
 df_2025_1, df_2025_2],
 ignore_index=True)

In [14]:
df_2024_1 = pd.read_csv('2024.1.csv', sep=';', decimal=',')
df_2024_1

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,5.93,NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,3.99,NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,5.48,NaN,R$ / litro,VIBRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477149,S,PR,CAMPO LARGO,AUTO POSTO IMPERADOR DE CAMPO LARGO LTDA,42.182.809/0001-21,RUA XAVIER DA SILVA,1596,NaN,CENTRO,83601-010,ETANOL,28/06/2024,3.99,NaN,R$ / litro,IPIRANGA
477150,NE,MA,CAXIAS,MAXXI PETRONORTE COMBUSTIVEIS E DERIVADOS LTDA,30.523.175/0001-44,RUA MANOEL GONCALVES,1458,NaN,CENTRO,65600-110,GASOLINA,28/06/2024,5.79,NaN,R$ / litro,BRANCA
477151,NE,MA,CAXIAS,MAXXI PETRONORTE COMBUSTIVEIS E DERIVADOS LTDA,30.523.175/0001-44,RUA MANOEL GONCALVES,1458,NaN,CENTRO,65600-110,GASOLINA ADITIVADA,28/06/2024,5.89,NaN,R$ / litro,BRANCA
477152,NE,MA,CAXIAS,MAXXI PETRONORTE COMBUSTIVEIS E DERIVADOS LTDA,30.523.175/0001-44,RUA MANOEL GONCALVES,1458,NaN,CENTRO,65600-110,DIESEL S10,28/06/2024,5.64,NaN,R$ / litro,BRANCA
477153,NE,MA,CAXIAS,MAXXI PETRONORTE COMBUSTIVEIS E DERIVADOS LTDA,30.523.175/0001-44,RUA MANOEL GONCALVES,1458,NaN,CENTRO,65600-110,ETANOL,28/06/2024,4.59,NaN,R$ / litro,BRANCA

In [20]:
df_2024_1= df.groupby('Revenda')['Valor de Venda'].mean().reset_index().sort_values(by= 'Valor de Venda',ascending = False)
df_2024_1

                                        Revenda  Valor de Venda
6181                L DA COSTA VASCONCELOS LTDA        8.370000
7765   POSTO DA PONTE COMERCIO DE PETROLEO LTDA        8.334727
4338           CENTRO AUTOMOTIVO GUARUJA 3 LTDA        8.223654
5448                         FGN COMERCIAL LTDA        8.223333
6364                  M C D CARVALHO & CIA LTDA        8.162628
...                                         ...             ...
1593             AUTO POSTO ESTACAO LESTE LTDA.        3.926765
3407            AUTO POSTO SHALLON ADONAI LTDA.        3.924375
7751                              POSTO CS LTDA        3.890000
10052            RFL CASTELINHO AUTO POSTO LTDA        3.823333
819                       AUTO POSTO BAOBA LTDA        3.790000

[10951 rows x 2 columns]

In [21]:
array_posto_241 = np.array(df_2024_1['Valor de Venda'])
array_posto_241

array([8.37      , 8.33472727, 8.22365385, ..., 3.89      , 3.82333333,
       3.79      ], shape=(10951,))

In [ ]:
media = np.mean(array_posto_241)
mediana = np.median(array_posto_241)